name = "views"
type = "javascript"
account_id = "f92057d66db62e6c5d714337ba723616"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-06-05"

[build]
command = "npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]

[env.production]
workers_dev = false
route = "https://views.aliu.dev/*"
zone_id = "5274e0bb9fb112a781d5aaa10f1dc293"
